name: simplebank

services:
  db:
    image: postgres:18
    container_name: simplebank-postgres
    restart: unless-stopped
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: simplebank
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-app} -d ${POSTGRES_DB:-appdb}" ]
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:8.2.3-alpine
    container_name: simplebank-redis
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - ./tmp/redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  postgres_data:
  redis_data:
